import argparse
import hashlib
import os
import struct
import sys

MAGIC = 0x31495746  # "FWI1"
HEADER_SIZE = 512
SIGNED_SIZE = 48
SIG_OFFSET = 48
SIG_SIZE = 64


def load_private_key(path):
    from cryptography.hazmat.primitives import serialization
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def public_bytes(key):
    numbers = key.public_key().public_numbers()
    return numbers.x.to_bytes(32, "big") + numbers.y.to_bytes(32, "big")


def cmd_pack(args):
    with open(args.input, "rb") as f:
        body = f.read()
    digest = hashlib.sha256(body).digest()
    header = struct.pack("<IIII", MAGIC, args.version, len(body), 0)
    header += digest + bytes(SIG_SIZE)
    header += b"\xff" * (HEADER_SIZE - len(header))
    with open(args.output, "wb") as f:
        f.write(header + body)
    print("packed %s: version %d, %d bytes of code, sha256 %s"
          % (args.output, args.version, len(body), digest.hex()))
    return 0


def cmd_keygen(args):
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import ec
    if os.path.exists(args.key):
        sys.exit("refusing to overwrite existing key " + args.key)
    os.makedirs(os.path.dirname(args.key) or ".", exist_ok=True)
    key = ec.generate_private_key(ec.SECP256R1())
    pem = key.private_bytes(serialization.Encoding.PEM,
                            serialization.PrivateFormat.PKCS8,
                            serialization.NoEncryption())
    with open(args.key, "wb") as f:
        f.write(pem)
    print("wrote private key to %s - keep it secret and out of Git" % args.key)
    return 0


def cmd_pubkey(args):
    raw = public_bytes(load_private_key(args.key))
    rows = []
    for i in range(0, len(raw), 8):
        rows.append("    " + ", ".join("0x%02x" % b for b in raw[i:i + 8]) + ",")
    text = ("/* Generated by tools/imgtool.py pubkey. Public key: safe to commit. */\n"
            "#include \"pubkey.h\"\n\n"
            "const uint8_t boot_public_key[64] = {\n" + "\n".join(rows) + "\n};\n")
    with open(args.output, "w", newline="\n") as f:
        f.write(text)
    print("wrote public key to", args.output)
    return 0


def cmd_sign(args):
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
    with open(args.input, "rb") as f:
        image = bytearray(f.read())
    if len(image) < HEADER_SIZE or struct.unpack_from("<I", image, 0)[0] != MAGIC:
        sys.exit("%s is not a packed image" % args.input)
    key = load_private_key(args.key)
    der = key.sign(bytes(image[:SIGNED_SIZE]), ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    image[SIG_OFFSET:SIG_OFFSET + SIG_SIZE] = r.to_bytes(32, "big") + s.to_bytes(32, "big")
    with open(args.output, "wb") as f:
        f.write(image)
    print("signed", args.output)
    return 0


def main():
    parser = argparse.ArgumentParser(description="Firmware image tool")
    sub = parser.add_subparsers(dest="command", required=True)

    pack = sub.add_parser("pack", help="add a header to a raw binary")
    pack.add_argument("input")
    pack.add_argument("output")
    pack.add_argument("--version", type=int, default=1)
    pack.set_defaults(func=cmd_pack)

    keygen = sub.add_parser("keygen", help="create a new private signing key")
    keygen.add_argument("key")
    keygen.set_defaults(func=cmd_keygen)

    pubkey = sub.add_parser("pubkey", help="write the public key as a C file")
    pubkey.add_argument("key")
    pubkey.add_argument("output")
    pubkey.set_defaults(func=cmd_pubkey)

    sign = sub.add_parser("sign", help="sign a packed image")
    sign.add_argument("--key", required=True)
    sign.add_argument("input")
    sign.add_argument("output")
    sign.set_defaults(func=cmd_sign)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
